SELECT RPAD(' ', (LEVEL-1)*4+1, '   ') || PSEUDO "Droga sluzbowa"
FROM KOCURY
CONNECT BY PRIOR SZEF=PSEUDO
START WITH PLEC='M' AND MYSZY_EXTRA IS NULL AND FLOOR(MONTHS_BETWEEN(DATE '2019-07-03', W_STADKU_OD)/12) >= 10