SELECT IMIE, TO_CHAR(W_STADKU_OD, 'YYYY-MM-DD') "W stadku", ROUND(NVL(PRZYDZIAL_MYSZY, 0)/1.1) Zjadal, TO_CHAR(ADD_MONTHS(W_STADKU_OD, 6),'YYYY-MM-DD')  Podwyzka, PRZYDZIAL_MYSZY Zjada
    FROM KOCURY
    WHERE FLOOR(MONTHS_BETWEEN(DATE '2019-07-03', W_STADKU_OD)/12) >= 10
        AND TO_CHAR(W_STADKU_OD, 'MM-DD') BETWEEN '03-01' AND '09-30';