SELECT IMIE, 3*NVL(PRZYDZIAL_MYSZY, 0) "MYSZY KWARTALNIE", 3*NVL(MYSZY_EXTRA, 0) "KWARTALNE DODATKI"
        FROM KOCURY
        WHERE NVL(PRZYDZIAL_MYSZY,0) > 2*NVL(MYSZY_EXTRA,0) AND NVL(PRZYDZIAL_MYSZY, 0) >= 55
        ORDER BY "MYSZY KWARTALNIE";