INSERT INTO Plebsy VALUES (1,'SZYBKA');
INSERT INTO Plebsy VALUES (2,'BOLEK');
INSERT INTO Plebsy VALUES (3,'LASKA');
INSERT INTO Plebsy VALUES (4,'MAN');
INSERT INTO Plebsy VALUES (5,'DAMA');
INSERT INTO Plebsy VALUES (6,'PLACEK');
INSERT INTO Plebsy VALUES (7,'RURA');
INSERT INTO Plebsy VALUES (8,'ZERO');
INSERT INTO Plebsy VALUES (9,'PUSZYSTA');
INSERT INTO Plebsy VALUES (10,'UCHO');
INSERT INTO Plebsy VALUES (11,'MALY');
INSERT INTO Plebsy VALUES (12,'MALA');


INSERT INTO Elity VALUES (1, 'TYGRYS', 5);
INSERT INTO Elity VALUES (2, 'LOLA', 9);
INSERT INTO Elity VALUES (3, 'ZOMBI', 4);
INSERT INTO Elity VALUES (4, 'LYSY', 1);
INSERT INTO Elity VALUES (5, 'KURKA', 10);
INSERT INTO Elity VALUES (6, 'RAFA', 7);


INSERT INTO Konta VALUES (1, 1, SYSDATE, NULL);
INSERT INTO Konta VALUES (2, 2, SYSDATE, NULL);
INSERT INTO Konta VALUES (3, 3, SYSDATE, NULL);
INSERT INTO Konta VALUES (4, 4, SYSDATE, NULL);
INSERT INTO Konta VALUES (5, 5, SYSDATE, NULL);
INSERT INTO Konta VALUES (6, 6, SYSDATE, NULL);
INSERT INTO Konta VALUES (7, 2, SYSDATE, NULL);
INSERT INTO Konta VALUES (8, 3, SYSDATE, NULL);
INSERT INTO Konta VALUES (9, 2, SYSDATE, NULL);
INSERT INTO Konta VALUES (10, 5, SYSDATE, NULL);
INSERT INTO Konta VALUES (11, 2, SYSDATE, NULL);

DROP TABLE DODATKI_EXTRA;