--Podpunkt a
SELECT K1.IMIE,
       NVL(K1.PRZYDZIAL_MYSZY, 0) + NVL(K1.MYSZY_EXTRA, 0) "ZJADA",
       K1.NR_BANDY "NR BANDY",
       AVG(NVL(K2.PRZYDZIAL_MYSZY, 0) + NVL(K2.MYSZY_EXTRA, 0)) "SREDNIA BANDY"
FROM KOCURY K1 JOIN KOCURY K2 on K1.NR_BANDY = K2.NR_BANDY AND
                              K1.PLEC='M'
GROUP BY K1.NR_BANDY, K1.IMIE, K1.PRZYDZIAL_MYSZY, K1.MYSZY_EXTRA
HAVING AVG(NVL(K1.PRZYDZIAL_MYSZY, 0) + NVL(K1.MYSZY_EXTRA, 0)) <= AVG(NVL(K2.PRZYDZIAL_MYSZY, 0) + NVL(K2.MYSZY_EXTRA, 0));

--Podpunkt b

SELECT K1.IMIE,
       NVL(K1.PRZYDZIAL_MYSZY, 0) + NVL(K1.MYSZY_EXTRA, 0) "ZJADA",
       K1.NR_BANDY "NR BANDY",
       "SREDNIA BANDY"
FROM KOCURY K1 JOIN (
                     SELECT AVG(NVL(PRZYDZIAL_MYSZY, 0) + NVL(MYSZY_EXTRA, 0)) "SREDNIA BANDY", NR_BANDY
                     FROM KOCURY
                     GROUP BY NR_BANDY
                    ) SR on K1.NR_BANDY = SR.NR_BANDY AND
                              K1.PLEC='M'
WHERE NVL(K1.PRZYDZIAL_MYSZY, 0) + NVL(K1.MYSZY_EXTRA, 0) <= "SREDNIA BANDY";
--Podpunkt c

SELECT K1.IMIE,
       NVL(K1.PRZYDZIAL_MYSZY, 0) + NVL(K1.MYSZY_EXTRA, 0) "ZJADA",
       K1.NR_BANDY "NR BANDY",
       (SELECT AVG(NVL(K2.PRZYDZIAL_MYSZY, 0) + NVL(K2.MYSZY_EXTRA, 0))
        FROM KOCURY K2
        WHERE K1.NR_BANDY=K2.NR_BANDY) "SREDNIA BANDY"
FROM KOCURY K1
WHERE K1.PLEC='M' AND NVL(K1.PRZYDZIAL_MYSZY, 0) + NVL(K1.MYSZY_EXTRA, 0) <= (SELECT AVG(NVL(K2.PRZYDZIAL_MYSZY, 0) + NVL(K2.MYSZY_EXTRA, 0))
                                                                              FROM KOCURY K2
                                                                              WHERE K1.NR_BANDY=K2.NR_BANDY)

