SELECT B.NAZWA "Nazwa bany", COUNT(DISTINCT W.IMIE_WROGA) "Koty z wrogami"
FROM KOCURY K JOIN BANDY B on K.NR_BANDY = B.NR_BANDY
    JOIN WROGOWIE_KOCUROW WK on K.PSEUDO = WK.PSEUDO
    JOIN WROGOWIE W on WK.IMIE_WROGA = W.IMIE_WROGA
GROUP BY B.NAZWA;