SELECT IMIE, 12*(NVL(PRZYDZIAL_MYSZY, 0) + MYSZY_EXTRA) "DAWKA ROCZNA", 'powyzej 864' "DAWKA"
FROM KOCURY
WHERE 12*(NVL(PRZYDZIAL_MYSZY, 0) + MYSZY_EXTRA) > 864 AND MYSZY_EXTRA IS NOT NULL
UNION
SELECT IMIE, 12*(NVL(PRZYDZIAL_MYSZY, 0) + MYSZY_EXTRA) "DAWKA ROCZNA", '864' "DAWKA"
FROM KOCURY
WHERE 12*(NVL(PRZYDZIAL_MYSZY, 0) + MYSZY_EXTRA) = 864 AND MYSZY_EXTRA IS NOT NULL
UNION
SELECT IMIE, 12*(NVL(PRZYDZIAL_MYSZY, 0) + MYSZY_EXTRA) "DAWKA ROCZNA", 'ponizej 864' "DAWKA"
FROM KOCURY
WHERE 12*(NVL(PRZYDZIAL_MYSZY, 0) + MYSZY_EXTRA) < 864 AND MYSZY_EXTRA IS NOT NULL
                                                           ORDER BY 2 DESC;