--podpunkt a

SELECT B.NR_BANDY "NR BANDY", B.NAZWA, B.TEREN
FROM BANDY B LEFT JOIN KOCURY K ON B.NR_BANDY = K.NR_BANDY
WHERE K.NR_BANDY IS NULL;

--podpunkt b

SELECT B.NR_BANDY "NR BANDY", B.NAZWA, B.TEREN
FROM BANDY B LEFT JOIN KOCURY K on B.NR_BANDY = K.NR_BANDY
MINUS
SELECT B.NR_BANDY "NR BANDY", B.NAZWA, B.TEREN
FROM BANDY B JOIN KOCURY K on B.NR_BANDY = K.NR_BANDY;