CREATE VIEW KOTY_SPOZ
AS
    SELECT B.NAZWA "NAZWA_BANDY",
           AVG(NVL(PRZYDZIAL_MYSZY, 0)) "SRE_SPOZ",
           MAX(NVL(PRZYDZIAL_MYSZY, 0)) "MAX_SPOZ",
           MIN(NVL(PRZYDZIAL_MYSZY, 0)) "MIN_SPOZ",
           COUNT(PSEUDO) "KOTY",
           COUNT(MYSZY_EXTRA) "KOTY_Z_DOD"
    FROM KOCURY K JOIN BANDY B on K.NR_BANDY = B.NR_BANDY
    GROUP BY B.NAZWA;


SELECT PSEUDO "PSEUDONIM",
       IMIE,
       FUNKCJA,
       PRZYDZIAL_MYSZY "ZJADA",'OD ' || MIN_SPOZ || ' DO ' || MAX_SPOZ "GRANICE SPOZYCIA",
       TO_CHAR(W_STADKU_OD, 'YYYY-MM-DD') "LOWI OD"
FROM KOCURY JOIN BANDY B ON KOCURY.NR_BANDY = B.NR_BANDY JOIN KOTY_SPOZ KS ON KS.NAZWA_BANDY = B.NAZWA
WHERE PSEUDO=${podany};
